-- Public downloads use unguessable object paths generated by the server.
-- No storage.objects policies are created: anon cannot list or write, while the
-- server-side service role can upload and manage objects.
insert into storage.buckets (id, name, public)
values
  ('help-request-photos', 'help-request-photos', true),
  ('info-resource-photos', 'info-resource-photos', true)
on conflict (id) do update
set name = excluded.name,
    public = excluded.public;
